name: akmods-nvidia-custom Builder
on:
  schedule:
    - cron: "0 3 * * *" # Codziennie w nocy nasz system budzi się by znaleźć nowości
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  matrix-spider:
    name: Cyber-Pająk Zwiadowca
    runs-on: ubuntu-latest
    outputs:
      fedora: ${{ steps.scrape.outputs.fedora }}
      nvidia: ${{ steps.scrape.outputs.nvidia }}
    steps:
      - name: Wykrywanie Najnowszych Wersji 
        id: scrape
        run: |
          # 1. Dynamiczne scrapowanie najnowszej stabilnej wersji Fedory
          FEDORA_VER=$(curl -sL https://dl.fedoraproject.org/pub/fedora/linux/releases/ | grep -oE 'href="[0-9]+/"' | grep -oE '[0-9]+' | sort -rn | head -n 1)
          
          # 2. Scrapowanie Oficjalnego endpointu najnowszej NVIDII (.run)
          NVIDIA_VER=$(curl -sL https://download.nvidia.com/XFree86/Linux-x86_64/latest.txt | awk '{print $1}')

          # 3. Dynamiczne pobieranie najnowszej stabilnej wersji jądra Linux
          LINUX_VER=$(curl -sL https://www.kernel.org/releases.json | jq -r '.latest_stable.version')
          
          echo "Znalazłem: Fedora=$FEDORA_VER, NVIDIA=$NVIDIA_VER, LINUX=$LINUX_VER"
          echo "fedora=$FEDORA_VER" >> "$GITHUB_OUTPUT"
          echo "nvidia=$NVIDIA_VER" >> "$GITHUB_OUTPUT"
          echo "linux=$LINUX_VER" >> "$GITHUB_OUTPUT"

  build:
    needs: matrix-spider
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Containerfile
          push: true
          tags: ghcr.io/vyzygota/akmods-nvidia-custom:latest
          build-args: |
            FEDORA_VERSION=${{ needs.matrix-spider.outputs.fedora }}
            NVIDIA_VERSION=${{ needs.matrix-spider.outputs.nvidia }}
